uses: AppImageCrafters/build-appimage@master
  with:
    recipe: "./appimage-demo-qt5/AppImageBuilder.yml"
  env:
    UPDATE_INFO: gh-releases-zsync|AppImageCrafters|appimage-demo-qt5|latest|*x86_64.AppImage.zsync